FROM debian:buster

ENV DEBIAN_FRONTEND noninteractive

RUN ln -snf /usr/share/zoneinfo/Etc/UTC /etc/localtime \
    && echo "Etc/UTC" > /etc/timezone \
    && apt-get update -q \
    && apt-get upgrade -qy \
    && apt-get install texlive-full python-pygments gnuplot -y \
    && rm -rf /var/lib/apt/lists/*